version: '3'

services:
  mysql-service:
     image: mysql:latest
     environment:
       MYSQL_ROOT_PASSWORD: "root"
       MYSQL_DATABASE: "testedb"
     ports:
       - "3306:3306"
     volumes:
       - mysql-vol:/var/lib/mysql
     networks:
       - my-stack-network

  phpmyadmin-service:
    image: phpmyadmin
    environment:
      PMA_HOST: mysql-service
    ports:
      - 8086:80
    networks:
      - my-stack-network
    depends_on:
      - mysql-service

  records-service:
    image: 'reinaldopadua/herbsjs-records'
    ports: 
      - 3109:3109
    depends_on:
      - mysql-service
    networks:
      - my-stack-network    

networks: 
  my-stack-network:
    driver: bridge

volumes:
  mysql-vol:
  mongodb-vol: